spring:
  application:
    name: itemsearchservice
    google:
      baseUrl: https://www.googleapis.com/books/v1/volumes
      metric: book.api.in.seconds
    iTunes:
      baseUrl: https://itunes.apple.com/search
      metric: album.api.in.seconds
    timeout: 3000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    ir.sk.item: DEBUG

resilience4j.circuitbreaker:
  instances:
    bookAPIService:
      registerHealthIndicator: true
      slidingWindowSize: 2
      waitDurationInOpenState: 1s
    albumAPIService:
      registerHealthIndicator: true
      slidingWindowSize: 2
      waitDurationInOpenState: 1s


resilience4j.retry:
  instances:
    bookAPIService:
      maxAttempts: 3
      waitDuration: 10s
    albumAPIService:
      maxAttempts: 3
      waitDuration: 10s

resilience4j.thread-pool-bulkhead:
  instances:
    bookAPIService:
      maxThreadPoolSize: 5
      coreThreadPoolSize: 2
      queueCapacity: 10
    albumAPIService:
      maxThreadPoolSize: 5
      coreThreadPoolSize: 2
      queueCapacity: 10

resilience4j.timelimiter:
  instances:
    bookAPIService:
      timeoutDuration: 3s # set timeout
    albumAPIService:
      timeoutDuration: 3s # set timeout